### PR TITLE
Updating jar and removing unused jars

### PR DESCRIPTION
**Pull request by jayasheelankumar**
Updating jar and removing unused jars

### CODE REVIEW

**Comment by jayasheelankumar** [comment]
The changes for JSP files and few other files are included. The copyright tool added the headers at the start of the file, which lead to JasperException in JSP file. I have manually replaced the headers in them.

**Comment by bshannon** [comment]
It looks like these .jsp files should really be .jspx files since they use XML syntax.
If you add an appropriate "<?xml ...>" line at the top, followed by the standard XML
copyright header, does that work?  Does it help if you rename the files to .jspx?

It looks like the example build.xml is trying to compile these JSP files, is that when
you get the JasperException?

**Comment by jayasheelankumar** [comment]
By adding appropriate "<?xml...>" line at the top and adding standard XML copyright header. I could build the project successfully.

Yes, in example build.xml we have a target which compile JSP files. It was exactly failing at that place.

Can I know just go ahead and add the XML based copyright header to all the files?

**Comment by bshannon** [comment]
Yes, please do that.

Jayasheelan Kumar wrote on 6/20/18 11:48 PM:

**Comment by jayasheelankumar** [comment]
Review changes are incorporated.

**Comment by bshannon** [comment]
Is it possible to rename these files from *.jsp to *.jspx so that the copyright tool will
know that they're supposed to be XML format files?  I'm not sure what would need
to be fixed in the build to make this work.

Also, the XML format header is wrong.  The lines are indented by the wrong amount of whitespace,
it should be 4 spaces only on each line.  Create a jspx file and run "cr -r" on it and you'll see what
the header should look like.

**Comment by jayasheelankumar** [comment]
Modified the extensions and also updated the correct copyright headers

**Comment by bshannon** [comment]
Did you really run the copyright tool after making all your changes?  I'm still seeing these errors:

./webui/jsp/help/buttonnav.jsp: WARNING: extra copyright:       Copyright 2007 Sun Microsystems, Inc. All rights reserved.
./webui/jsp/help/helpwindow.jsp: WARNING: extra copyright:       Copyright 2007 Sun Microsystems, Inc. All rights reserved.
./webui/jsp/help/navigator.jsp: WARNING: extra copyright:       Copyright 2007 Sun Microsystems, Inc. All rights reserved.
./webui/jsp/help/tips.jsp: WARNING: extra copyright:       Copyright 2007 Sun Microsystems, Inc. All rights reserved.
./webui/src/runtime/com/sun/webui/jsf/util/MethodBindingMethodExpressionAdapter.java: WARNING: extra copyright:  * Copyright 2005 Sun Microsystems Inc. All Rights Reserved
./webui/src/runtime/com/sun/webui/jsf/util/MethodExpressionMethodBindingAdapter.java: WARNING: extra copyright:  * Copyright 2005 Sun Microsystems Inc. All Rights Reserved

Also, I suspect these files are defined by Woodstock and not by any JCP standard, and thus the copy/license header of these files can be updated:

./webui/lib/jsfmetadata-conf/web-facesconfig-overlay_1_0.dtd: Wrong copyright
./webui/lib/jsfmetadata-conf/web-facesconfig-overlay_1_1.dtd: Wrong copyright
./webui/lib/jsfmetadata-conf/web-facesconfig-overlay_1_2.dtd: Wrong copyright

Finally, this file can be removed because it's no longer relevant:

./doc/licenses/CDDLv1.0.txt

Instead, our standard LICENSE.txt or LICENSE.md file should be added to the top of the repository.

**Comment by jayasheelankumar** [comment]
Reverified and made suitable changes. Also have incorporated the comments.

**Comment by bshannon** [comment]
Close.  The LICENSE.md file has a copyright/license header, which should be removed.

**Comment by jayasheelankumar** [comment]
copyright/license header changes are removed from LICENSE.md file

**Pull request merged**
